### ISSUE TITLE
v2.ODataModel Object.keys(...).values is not a function

### ISSUE THREAD

**Issue by MichaelFlucher** [ArnaudBuchholz/node-ui5#6]
Using the Code you suggest in readme.md I can't get the ODataModel to work. I always get
TypeError: Object.keys(...).values is not a function at U.keys (https://openui5.hana.ondemand.com/resources/sap-ui-core.js:238:338)

It doesn't matter if I use the CDN or not. The behavior also doesn't change if I pass an empty URL to the ODataModel constructor.

**Comment by ArnaudBuchholz** [comment]
@MichaelFlucher would you mind sharing your code?

**Comment by MichaelFlucher** [comment]
I'm sorry, but I don't have the code anymore. Anyway I started a new project and now I got it to work.
Maybe because I installed jsdom, @openui5/sap.ui.core and @ui5/cli before node-ui5?

**Comment by ArnaudBuchholz** [comment]
@MichaelFlucher I have seen this error sometimes when someone uses the following code:
sap.ui.define([
  "sap/ui/base/Object"
], function (Object) {
  // By doing so, you override the native Object class, which is wrong...
});
